### ISSUE TITLE
Create check for Password and Confirm Password in the Sign up page.

### ISSUE THREAD

**Issue by anurag8546** [harshit21-02/AB-Chat#3]
Current Behavior:
When a user registers on the app, the user fills password again on "Confirm Password" box. But if the user enters wrong password it doesn't detect it.
Required Behavior:
Detect whether password matches with confirm password or not?

**Comment by harshit21-02** [comment]
Okay! I will work on this issue

**Comment by anurag8546** [comment]
Okay @harshit21-02 . I'm assigning it to you.
 : )
